---
apiVersion: v1
kind: Pod
metadata:
  name: multitool
  labels:
    app: multitool
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool
      ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
