---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-multitool
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 9001
      - name: multitool
        image: wbitt/network-multitool
        env: 
          - name: HTTP_PORT
            value: "1180"
          - name: HTTPS_PORT
            value: "11443"
        ports:
        - containerPort: 9002
        - containerPort: 9003
