---
- name: Install EPEL Repo
  yum:
    name=epel-release
    state=present
- name: Install git and nginx
  ansible.builtin.yum:
    name:
      - git
      - nginx
  notify:
      - Nginx systemd
- name: Replace nginx.conf
  ansible.builtin.template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0755'
- name: Create home directory for www
  ansible.builtin.file:
    path: /opt/www/lighthouse/
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'
  notify:
    - Nginx restart
- name: Download lighthouse
  ansible.builtin.git:
    repo: https://github.com/VKCOM/lighthouse.git
    dest: /opt/www/lighthouse/
#- name: Change owner directory
#  ansible.builtin.command: sudo chown -R nginx:nginx /opt/www/lighthouse/
