---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-multitool
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env: 
          - name: HTTP_PORT
            value: "1180"
          - name: HTTPS_PORT
            value: "11443"
        ports:
        - containerPort: 1180
        - containerPort: 11443


# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-svc
# spec:
#   ports:
#   - protocol: TCP
#     name: mult-1180
#     port: 1180
#     targetPort: 1180
#   - protocol: TCP
#     name: mult-11443
#     port: 11443
#     targetPort: 11443
#   selector:
#     app: nginx