---
apiVersion: v1
kind: Service
metadata:
  name: nginx-services
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mydb
# spec:
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 9377